trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: candy_env
  displayName: CANdy Network Environment
  type: string
  default: dev
  values:
  - dev
  - stage
  - prod

steps:
- task: DownloadSecureFile@1
  name: download_ssh_key
  inputs:
    secureFile: 'di-candy-test-run.pem'

- script: |
    ls -lah
    ls -lah $(download_ssh_key.secureFilePath)
    # sudo find / -type f -name di-candy-test-run.pem
    ln -sn $(download_ssh_key.secureFilePath) /tmp/di-candy-test-run.pem  
    # git clone https://github.com/donato-ods-devops/Candy.git
    # ls -lah
    ls -lah /tmp
  displayName: "Symlink the SSH key"

  # - job: ping_servers
  #   dependsOn: prep
  #   steps:
  #   - script: |
  #       ansible -i inventories/${{ parameters.candy_env }}/inventory.yml nodes -m ping
  #     displayName: 'Ping the servers in the inventory file'

  # - job: remove_stuff
  #   dependsOn: ping_servers
  #   steps:
  #   - script: |
  #       rm -rf Candy
  #       rm -rf /tmp/di-candy-test-run.pem
  #     displayName: 'Remove stuff'

  # - job: cleanup
  #   dependsOn: ping_servers
  #   condition: failed()
  #   displayName: Cleanup on Failure
  #   steps:
  #   - script:
  #       rm -rf Candy
  #       rm -rf /tmp/di-candy-test-run.pem