trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: candy_env
  displayName: CANdy Network Environment
  type: string
  default: dev
  values:
  - dev
  - stage
  - prod

stages:
- stage:
  jobs:
  - job: download_ssh_key
    displayName: "Download the ssh key."
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'di-candy-test-run.pem'
  
  - job: symlink_ssh_key
    displayName: "Symlink the SSH key"
    steps:
    - bash: |
        ln -sn $(download_ssh_key.secureFilePath) /tmp/di-candy-test-run.pem  

  - job: git_clone_candy_repo
    displayName: "Git clone the CANDy repository"
    steps:
    - bash: |
        git clone https://github.com/donato-ods-devops/Candy.git

  - job: list_working_directory
    displayName: "List the working directory"
    steps:
    - bash: |
        ls -lah

  - job: ping_servers
    displayName: 'Ping the servers in the inventory file'
    steps:
    - bash: |
        ansible -i inventories/${{ parameters.candy_env }}/inventory.yml nodes -m ping

  - job: remove_stuff
    steps:
    - bash: |
        rm -rf Candy
        rm -rf /tmp/di-candy-test-run.pem

  - job: cleanup
    dependsOn: ping_servers
    condition: failed()
    displayName: Cleanup on Failure
    steps:
    - bash:
        rm -rf Candy
        rm -rf /tmp/di-candy-test-run.pem