# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: candy_env
    displayName: CANdy Network Environment
    type: string
    default: dev
    values:
      - dev
      - stage
      - prod

steps:
  - task: DownloadSecureFile@1
    name: download_ssh_key
    inputs:
      secureFile: 'di-candy-test-run.pem'
    displayName: "Download the ssh key."

  - bash: |
      ln -sn $(download_ssh_key.secureFilePath) ./di-candy-test-run.pem
    displayName: "Symlink the SSH key"

  - bash: |
      git clone https://github.com/donato-ods-devops/Candy.git
    displayName: "Git Clone the CANDy repository"

  - bash: |
      ansible -i inventories/${{ parameters.candy_env }}/inventory.yml nodes -m ping
    displayName: 'Run bash script'

  - bash: |
      rm -rf Candy
      rm -rf *.pem
