trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: candy_env
  displayName: CANdy Network Environment
  type: string
  default: dev
  values:
  - dev
  - stage
  - prod

steps:
- task: DownloadSecureFile@1
  name: download_ssh_key
  inputs:
    secureFile: 'di-candy-test-run.pem'

- script: |
    ls -lah
    ls -lah $(download_ssh_key.secureFilePath)
    cp $(download_ssh_key.secureFilePath) ./di-candy-test-run.pem
    chmod 0600 ./di-candy-test-run.pem
    ls -lah /tmp
    git clone https://github.com/donato-ods-devops/Candy.git
    ansible -vvvv -i inventories/${{ parameters.candy_env }}/inventory.yml --private-key ./di-candy-test-run.pem nodes -m ping
  displayName: 'Ping the servers in the inventory file'
  name: ping_servers

- script: |
    rm -rf Candy
    rm -rf /tmp/di-candy-test-run.pem
    rm -rf $(download_ssh_key.secureFilePath)
  displayName: 'Cleanup on Success'
  condition: succeeded()
  name: cleanup_success
  
- script:
    rm -rf Candy
    rm -rf /tmp/di-candy-test-run.pem
    rm -rf $(download_ssh_key.secureFilePath)
  condition: failed()
  displayName: Cleanup on Failure