# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: inventory_file
  inputs:
    secureFile: 'candy-inventory.yml'
  displayName: "Download the inventory file."

- bash: |
    ls -lah
  displayName: "List the directory"

- bash: |
    chmod +x script.sh
    ./script.sh $(inventory_file.secureFilePath)
  displayName: 'Run bash script'
